import type { Metadata } from "next";
import { geistSans, geistMono } from "@/shared/assets/fonts/fonts";
import { ReactQueryProvider } from '@/core/providers/react-query-provider';
import "../shared/styles/globals.css";

import { Header } from '@/components/layout/Header/Header'
// import { Footer } from '@/components/layout/Footer'

export const metadata: Metadata = {
  title: "Create Next App", 
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ReactQueryProvider>
          <Header />
          <main>{children}</main>
        {/* <Footer /> */}
        </ReactQueryProvider>
      </body>
    </html>
  );
}